name: ABN - I14Y CHOP Importer
permissions:
  contents: read

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  import-chop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run CHOP Importer script
      env:
        CLIENT_KEY: ${{ secrets.CLIENT_ID_ABN }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_ABN }}
        GET_TOKEN_URL: "https://identity-a.bit.admin.ch/realms/bfs-sis-a/protocol/openid-connect/token"
        I14Y_API_BASE_URL: "https://api-a.i14y.admin.ch/api/partner/v1"
        CHOP_YEAR: ${{ vars.CHOP_YEAR }}
        CHOP_REVISION: ${{ vars.CHOP_REVISION }}
      run: python CHOPImporter.py